version: 0.2

env:
  variables:
    REPOSITORY_URI: "584643220196.dkr.ecr.us-east-2.amazonaws.com/dev-portal-ui"
    IMAGE_TAG: "0.1.0-SNAPSHOT"

phases:
  build:
    commands:
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker images...
      - $(aws ecr get-login --region us-east-2 --no-include-email)
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
