export interface FRUser {
    _id ? :  string ,
    _rev ? :  string ,
    username ? :  string ,
    realm ? :  string ,
    telephoneNumber ? :  string[] ,
    mail ? :  string[] ,
    displayName ? :  string[] ,
    distinguishedName ? :  string[] ,
    dn ? :  string[] ,
    employeeID ? :  string[] ,
    objectGUID ? :  string[] ,
    sn ? :  string[] ,
    memberOf ? :  string[] ,
    department ? :  string[] ,
    userAccountControl ? :  string[] ,
    userPrincipalName ? :  string[] ,
    extensionAttribute14 ? :  string[] ,
    c ? :  string[] ,
    sAMAccountName ? :  string[] ,
    extensionAttribute4 ? :  string[] ,
    givenName ? :  string[] ,
    objectClass ? :  string[] ,
    createTimeStamp ? :  string[] ,
    cn ? :  string[] ,
    modifyTimeStamp ? :  string[] ,
    co ? :  string[] ,
    universalid ? :  string[] ,
    businessCategory ? :  string[] ,
    name ? :  string[] ,
    inetUserStatus ? :  string[] ,
    pwdLastSet ? :  string[] ,
    roles ? :  string[]
}